name: Larastan

on:
  push:
    branches:
      - '*'
    paths:
      - '**.php'

jobs:
  phpstan:
    strategy:
      matrix:
        php: ['8.2']
        laravel: ['^10.0']
      fail-fast: false

    name: 'P${{ matrix.php }} - L${{ matrix.laravel }}'

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'

      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php }}'
          extensions: 'dom, curl, libxml, mbstring, zip, fileinfo'
          coverage: 'none'

      - name: 'Change Composer config minimum-stability'
        run: 'composer config minimum-stability stable'

      - name: 'Change Composer config prefer-stable'
        run: 'composer config prefer-stable false'

      - name: 'Require Larastan dev version'
        run: 'composer require larastan/larastan:@dev --no-update --no-interaction --no-progress'

      - name: 'Install highest dependencies from composer.json'
        run: "composer update --with='laravel/framework:${{ matrix.laravel }}' --no-interaction --no-progress"

      - name: 'Execute static analysis'
        run: 'composer run-script analyse'
